{
 "title": "Github Copilot",
 "tags": [
  "GitHub",
  "Copilot"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "type": "canvas", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "Acceptance rate today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_acceptances_count / github_copilot_total_suggestions_count * 100",
     "legendFormat": "Acceptance rate today"
    }
   ]
  },
  {
   "title": "Acceptance rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "github_copilot_total_acceptances_count / github_copilot_total_suggestions_count * 100",
     "legendFormat": "Total Acceptances"
    }
   ]
  },
  {
   "title": "Users by editor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (editor) (github_copilot_active_users_by_language_editor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (language) (github_copilot_lines_suggested_by_language_editor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Lines Suggested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_copilot_total_lines_suggested",
     "legendFormat": "Total Lines Suggested"
    }
   ]
  },
  {
   "title": "Total Chat Turns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "github_copilot_total_chat_turns",
     "legendFormat": "Chat turns"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(github_copilot_total_active_chat_users + github_copilot_total_active_users)",
     "legendFormat": "Active users"
    }
   ]
  }
 ]
}